name: inception

volumes:
  wp-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/iury/data/wp-database

  wp-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/iury/data/wp-files

services:
  mariadb:
    container_name: mariadb-container
    pull_policy: build
    image: "mariadb-image:inception"
    build:
      # no_cache: true
      context: requirements/mariadb
      args:
        - WP_DATABASE_NAME
        - WP_DATABASE_USER
        - WP_DATABASE_PASSWORD
    networks:
      - inception-network
    volumes:
      - wp-database:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress-container
    pull_policy: build
    image: "wordpress-image:inception"
    build:
      # no_cache: true
      context: requirements/wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wp-files:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx-container
    pull_policy: build
    image: "nginx-image:inception"
    build:
      context: requirements/nginx
    env_file: .env
    networks:
      - inception-network
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/wordpress
    depends_on:
      - wordpress
      - adminer
    restart: always

  adminer:
    container_name: adminer-container
    pull_policy: build
    image: "adminer-image:inception"
    build:
      context: bonus/adminer
    networks: 
    - inception-network
    restart: always

  ftp:
    container_name: ftp-container
    pull_policy: build
    image: "ftp-image:inception"
    build:
      context: bonus/ftp
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception-network
    depends_on:
      - wordpress
    restart: always

  site:
    container_name: site-container
    pull_policy: build
    image: "site-image:inception"
    build:
      context: bonus/site
    networks:
      - inception-network
    depends_on:
      - nginx
    restart: always

networks:
  inception-network:
    driver: bridge
    name: Inception Network
